name: Lint and Format Protobuf Files

on:
  pull_request:
    paths:
      - "**.proto"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1.50.0
        with:
          version: 1.50.0

      - name: Check buf version
        run: buf --version

      - name: Run buf lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: proto

      - name: Check formatting
        run: buf format --exit-code --diff
